CREATE DATABASE burger_db;
USE burger_db;

CREATE TABLE burger(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    eaten BOOLEAN DEFAULT false,
    note VARCHAR(255) DEFAULT ""
)